Fix `tests/test_extract/test_cli_extractor.py:313: DeprecationWarning: Name.__init__ missing 1 required positional argument: 'id'. This will become an error in Python 3.15.`